"""
Database Repository: Alert Preferences.

This module handles CRUD operations for anonymous browser-level alert preferences.
Users can configure custom PM2.5 threshold limits without needing an account.
"""

from decimal import Decimal
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models.alert_preference import AlertPreference


class AlertPreferenceRepository:
    """Repository class to read and update user alert threshold settings."""

    def __init__(self, session: Session) -> None:
        """Initialize repository with an active database session."""
        self._session = session

    def get(self, browser_id: UUID) -> AlertPreference | None:
        """
        Look up alert preference by unique browser UUID.

        Args:
            browser_id: Unique anonymous client identifier generated by the frontend.

        Returns:
            AlertPreference model if found, or None.
        """
        return self._session.scalar(
            select(AlertPreference).where(AlertPreference.browser_id == browser_id)
        )

    def upsert(
        self, *, browser_id: UUID, threshold_ug_m3: Decimal, enabled: bool
    ) -> AlertPreference:
        """
        Create or update an alert preference for the given browser UUID.

        Args:
            browser_id: Anonymous browser client UUID.
            threshold_ug_m3: PM2.5 limit in ug/m3 above which alert triggers.
            enabled: Boolean flag indicating if alert is turned on.

        Returns:
            Saved or updated AlertPreference record.
        """
        preference = self.get(browser_id)
        if preference is None:
            # Create a new preference record if one does not exist
            preference = AlertPreference(
                browser_id=browser_id,
                threshold_ug_m3=threshold_ug_m3,
                enabled=enabled,
            )
            self._session.add(preference)
        else:
            # Update the existing preference
            preference.threshold_ug_m3 = threshold_ug_m3
            preference.enabled = enabled
        self._session.flush()
        return preference
