"""Alert preference database model.

Stores client-side browser alert thresholds for high PM2.5 levels.
Preserves privacy by using an anonymous UUID without requiring user accounts or PII.
"""

from datetime import datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import Boolean, CheckConstraint, DateTime, Numeric, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class AlertPreference(Base):
    """SQLAlchemy model for the 'alert_preferences' table."""

    __tablename__ = "alert_preferences"

    # Constraints
    __table_args__ = (
        # Ensure only one preference record per browser client ID
        UniqueConstraint("browser_id", name="uq_alert_preferences_browser_id"),
        # Valid PM2.5 threshold range between 1 and 2000 µg/m³
        CheckConstraint(
            "threshold_ug_m3 > 0 AND threshold_ug_m3 <= 2000",
            name="ck_alert_preferences_threshold_range",
        ),
    )

    # Primary key: UUID v4
    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)

    # Anonymous client browser UUID generated by the frontend
    browser_id: Mapped[UUID] = mapped_column(nullable=False)

    # User-chosen PM2.5 alert trigger threshold in µg/m³
    threshold_ug_m3: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)

    # Active status switch (True = enabled, False = muted/disabled)
    enabled: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="true"
    )

    # Timestamp of latest modification
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
