"""Stored user-facing PM2.5 forecast outputs."""

from datetime import datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Integer, Numeric, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class Forecast(Base):
    """One forecast horizon generated by a successful forecast run."""

    __tablename__ = "forecasts"
    __table_args__ = (
        UniqueConstraint("forecast_run_id", "horizon_hours", name="uq_forecasts_run_horizon"),
        CheckConstraint("horizon_hours IN (1, 6, 24)", name="ck_forecasts_supported_horizon"),
        CheckConstraint("predicted_value_ug_m3 >= 0", name="ck_forecasts_non_negative_prediction"),
        CheckConstraint("lower_bound_ug_m3 >= 0", name="ck_forecasts_non_negative_lower_bound"),
        CheckConstraint("upper_bound_ug_m3 >= lower_bound_ug_m3", name="ck_forecasts_ordered_bounds"),
    )

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    forecast_run_id: Mapped[UUID] = mapped_column(
        ForeignKey("forecast_runs.id", ondelete="RESTRICT"), nullable=False
    )
    horizon_hours: Mapped[int] = mapped_column(Integer, nullable=False)
    target_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    predicted_value_ug_m3: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    lower_bound_ug_m3: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    upper_bound_ug_m3: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
